### ISSUE TITLE
Mouse Back Buttons don't work in Unity 2020.3

### ISSUE THREAD

**Issue by michaelclockstone** [garettbass/UnityExtensions.SelectionHistory#1]
unfortunatel no mouse events for back/forward buttons are received by GUIUtility.processEvent

**Comment by garettbass** [comment]
This is a Unity limitation.  Some platform specific code would be required, and I haven’t found a reliable solution.  Pull requests are welcome.

**Comment by Manamongods** [comment]
This AutoHotkey script works for me so far:


#IfWinActive ahk_exe Unity.exe
XButton1::^[

#IfWinActive ahk_exe Unity.exe
XButton2::^]


And putting a shortcut to it inside %appdata%\Microsoft\Windows\Start Menu\Programs\Startup so it starts on startup

**Comment by garettbass** [comment]
I’ve noticed Unity editor doesn’t generate GUI events for back/forward buttons on mouse.  Good workaround!
